## Jekyll configs
permalink: /:year/:month/:day/:title/
highlighter: rouge
kramdown: 
  parse_block_html: true
sass:
  style: :compressed
plugins:
  - jemoji
  - jekyll-sitemap

## Site structure
collections:
  testimonials:
    output: true
    permalink: /testimonials/:title/
  classes:
    output: true
    permalink: /classes/:path/
  autopages:
    output: true
    permalink: /:title/
  forms:
    output: true
    permalink: /forms/:title/

defaults:
  -
    scope:
      path: ""
      type: "autopages" # a collection in your site, in plural form
    values:
      layout: "autopage"
  -
    scope:
      path: ""
      type: "classes"
    values:
      layout: "class"
  -
    scope:
      path: ""
      type: "testimonials"
    values:
      layout: "testimonial"
  -
    scope:
      path: ""
      type: "forms"
    values:
      layout: "form"

## Basic site info
title: FIDO Personal Dog Training
primary_author: "FIDO Personal Dog Training, LLC."
shortname: Fido
baseurl: http://fidodogtraining.com
email: fidofetch@sbcglobal.net
phone: 248-607-9350
gaid: UA-12803971-1

## Open Graph
og_street_address: 23440 Woodward Ave
og_locality: Ferndale
og_region: MI
og_postal_code: "48220"
og_country: USA
